- set_fact: role_name=home-web

- name: install nodejs
  include: ../../../tasks/install_node.yml

- name: create www root folder
  file: path={{ www_dir }} state=directory

- name: link www project root folder
  file: src=/vagrant/www dest=/var/www/home-web state=link

- npm: name=brunch global=yes

- name: install app dependencies
  command: npm cache clean && npm install --unsafe-perm
  args:
        chdir: "{{ www_dir }}/{{ role_name }}"
        creates: "{{ www_dir }}/{{ role_name }}/node_modules"

- command: brunch build creates={{ www_dir }}/{{ role_name }}/public/js/app.js
