- set_fact: role_name=home-web

- name: install node
  include: ../../../tasks/install_node.yml

- name: create www root folder
  file: path={{ www_dir }} state=directory

- name: link www project root folder
  file: src=/vagrant/www dest=/var/www/home-web state=link

# - name: install app dependencies
#   npm: path={{ www_dir }}/{{ role_name }} production={{ "no" if is_development_environment else "yes" }}

# - name: install app dependencies
#   command: npm cache clean && npm install --unsafe-perm
#   args:
#         chdir: "{{ www_dir }}/{{ role_name }}"
#         creates: "{{ www_dir }}/{{ role_name }}/node_modules"
