- set_fact: role_name=home-web

- name: install nodejs
  include: ../../../tasks/install_node.yml

- name: create www root folder
  file: path={{ www_dir }} state=directory

- name: link www project root folder
  file: src=/vagrant/www dest=/var/www/home-web state=link

# Windows hosts won't handle creating an actual dir, but it's ok to create a symlink
- file: path=/tmp/node_modules state=directory
- file: src=/tmp/node_modules dest={{ www_dir }}/{{ role_name }}/node_modules state=link

- name: install npm modules
  shell: npm install
  args:
    chdir: "{{ www_dir }}/{{ role_name }}"
    creates: "{{ www_dir }}/{{ role_name }}/node_modules"

- name: install app configuration
  template: src=cocorico.json.j2 dest=/etc/cocorico.json

- name: create admin user
  when: is_development_environment
  shell: ./node_modules/headstone/cli.js {{ www_dir }}/{{ role_name }}/scripts/add-user.js --cwd={{ www_dir }}/{{ role_name }} --userEmail={{ home_web_admin_email }} --userPassword={{ home_web_admin_password }} --userName={{ home_web_admin_name }} --userIsAdmin=true
  # shell: headstone {{ www_dir }}/{{ role_name }}/scripts/add-user.js --cwd={{ www_dir }}/{{ role_name }} --userEmail={{ home_web_admin_email }} --userPassword={{ home_web_admin_password }} --userName={{ home_web_admin_name }} --userIsAdmin=true
  args:
    chdir: "{{ www_dir }}/{{ role_name }}"
  register: result
  changed_when: "'created' in result.stdout"
  failed_when: result.stderr

- name: install upstart script
  template: src={{ role_name }}.upstart.conf.j2 dest=/etc/init/{{ role_name }}.conf
  notify:
    - restart home-web service

- name: install redis server
  apt: name=redis-server state=present
