sudo: required
dist: trusty

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="image"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="docker"

script:
  - sudo ln -s $TRAVIS_BUILD_DIR /vagrant
  - cd /vagrant && sudo bash ./deployment/ansible.sh
