sudo: required
dist: trusty

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="local"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="travis"

script:
  - ln -s $TRAVIS_BUILD_DIR /vagrant
  - cd /vagrant && source "deployment/ansible.sh"
