sudo: required
dist: trusty
language: generic

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="local"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="travis"

# script:
#   - sudo ln -s $TRAVIS_BUILD_DIR /vagrant
#   - cd /vagrant && sudo bash ./deployment/ansible.sh
#   - sudo ./script/run-tests.sh

after_success:
  - ./script/deploy-prod.sh

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/37692dce0ad99c8a2c7d
    on_success: change
    on_failure: always
    on_start: never

before_install:
  - openssl aes-256-cbc -K $encrypted_1f753eb353f1_key
    -iv $encrypted_1f753eb353f1_iv
    -in provisioning/inventory/group_vars/prod.yml.enc
    -out provisioning/inventory/group_vars/prod.yml -d
