sudo: required
dist: trusty

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="local"
    - SKIP_TAGS=""
    - VERBOSE="vvv"

script:
  - source "deployment/ansible.sh"
