sudo: required
dist: trusty

language: generic

env:
  global:
    - PLAYBOOK="provisioning/provision.yml"
    - INVENTORY="provisioning/inventory"
    - LIMIT="travis"
    - SKIP_TAGS=""
    - VERBOSE="vvv"
    - PROVIDER="travis"

script:
  - sudo ln -s $TRAVIS_BUILD_DIR /vagrant
  - cd /vagrant && sudo bash ./deployment/ansible.sh
  - sudo ./script/run-tests.sh
