- set_fact: role_name=blockchain-worker

- name: install nodejs
  include: ../../../tasks/install_node.yml

- name: create role directory
  file: path={{ project_dir}}/{{ role_name }} state=directory

- file: path={{ project_dir }}/{{ role_name }}/node_modules state=directory recurse=yes
- file: src={{ project_dir }}/{{ role_name }}/node_modules dest=/vagrant/{{ role_name }}/node_modules state=link

- name: install npm modules
  npm: path=/vagrant/blockchain-worker

- name: install leader upstart script
  template: src={{ role_name }}.upstart.conf.j2 dest=/etc/init/{{ project_name }}-{{ role_name }}.conf

- name: install follower upstart scripts
  template: src={{ role_name }}-{{ item }}.upstart.conf.j2 dest=/etc/init/{{ project_name }}-{{ role_name }}-{{ item }}.conf
  with_items:
    - ballot
    - vote

- name: restart the worker services
  service: name=cocorico-blockchain-worker state=restarted
