- set_fact: role_name=api-db

- name: install mongodb
  apt: name={{ item }} state=present
  with_items:
    - mongodb

- name: open mongodb to external services
  lineinfile: dest=/etc/mongodb.conf regexp=^bind_ip line="bind_ip = 0.0.0.0"
  when: is_development_environment
  notify:
    - restart mongodb service

- name: test if mongo is locked
  stat: path=/var/lib/mongo/mongod.lock
  register: result

- name: start mongodb service
  shell: /etc/init.d/mongodb start
  args:
    creates: /var/lib/mongo/mongod.lock
  when:
    - not result.stat.exists
    - provider == 'docker'
