---
- set_fact: role_name=front-web

- name: install apache2
  apt: name={{ item }} state=present
  with_items:
    - apache2

- name: enable apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - deflate
    - filter
    - headers
    - proxy
    - proxy_http
    - proxy_wstunnel
    - ssl
    - rewrite

- name: disable apache modules
  apache2_module: name={{ item }} state=absent
  with_items:
    - autoindex
  notify:
    - restart apache2 service

- name: install hosts
  lineinfile: dest=/etc/hosts line='{{ item }}'
  with_items:
    - "127.0.0.1 localhost"
    - "127.0.0.1 {{ front_web_public_host }} {{ front_hostname }} {{ project_name }} {{ hostname }}"
  when:
    - provider != 'docker'

- name: install htpasswd
  copy: src=.htpasswd dest=/etc/apache2/.htpasswd
  when: environment_name == 'staging'

- name: create the certbot install dir
  file: path={{ certbot_dir }} state=directory
  when: certbot_enabled

- name: install certbot
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: "{{ certbot_dir }}"
    mode: a+x
  when:
    - certbot_enabled
    - http_protocol_prefix == 'https'

- stat: path=/etc/letsencrypt/live/{{ front_web_public_host }}/cert.pem
  register: letsencrypt_ssl_certificate
  when: certbot_enabled

- name: stop apache2
  service: name=apache2 state=stopped
  when:
    - certbot_enabled
    - not letsencrypt_ssl_certificate.stat.exists

- name: install letsencrypt SSL certificates
  shell: "{{ certbot_dir }}/certbot-auto certonly --standalone --noninteractive --text --agree-tos --email {{ certbot_email }} --domains {{ front_web_public_host }}"
  when:
    - certbot_enabled
    - not letsencrypt_ssl_certificate.stat.exists

- name: create cron job to renew letsencrypt certificates
  cron:
    name: "renew letsencrypt certificates"
    state: "{{ certbot_renew | ternary('present', 'absent') }}"
    special_time: daily
    job: "{{ certbot_dir }}/certbot-auto renew --quiet --no-self-upgrade"
  when:
    - certbot_enabled
    - http_protocol_prefix == 'https'

- name: install site configuration
  template: src={{ project_name }}-{{ role_name }}.conf.j2 dest=/etc/apache2/sites-available/{{ project_name }}-{{ role_name }}.conf
  notify:
    - restart apache2 service

- name: enable site
  file: src=/etc/apache2/sites-available/{{ project_name }}-{{ role_name }}.conf dest=/etc/apache2/sites-enabled/{{ project_name }}-{{ role_name }}.conf state=link
  notify:
    - restart apache2 service

- name: disable default vhost
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache2 service

- name: delete default html files
  file: path=/var/www/html state=absent

- name: create ssl directory
  file: path=/etc/apache2/ssl state=directory

- name: create include directory
  file: path=/etc/apache2/sites-available/{{ project_name}}-{{ role_name }}-include state=directory

- name: create self-signed certificate
  shell: openssl req -new -nodes -x509 -subj "/C=FR/ST=IdF/L=Paris/O=IT/CN={{ front_web_public_host }}" -days 3650 -keyout /etc/apache2/ssl/{{ front_hostname }}.key -out /etc/apache2/ssl/{{ front_hostname }}.crt -extensions v3_ca
  args:
    creates: /etc/apache2/ssl/{{ front_hostname }}.crt
  when:
    - is_development_environment
    - http_protocol_prefix == 'https'
  notify:
    - restart apache2 service

- name: remove unused sites
  file: path=/etc/apache2/sites-available/{{ item }} state=absent
  with_items:
    - 000-default.conf
    - default-ssl.conf

- name: set global server name
  lineinfile: dest=/etc/apache2/apache2.conf line='ServerName localhost'
