---
- set_fact: role_name=api-web

- name: install nodejs
  include: ../../../tasks/install_node.yml

- name: create root folder
  file: path={{ project_dir }}/{{ role_name }} state=directory

# Windows hosts won't handle creating an actual dir, but it's ok to create a symlink
- file: path={{ project_dir }}/{{ role_name }}/node_modules state=directory recurse=yes
- file: src={{ project_dir }}/{{ role_name }}/node_modules dest={{ cocorico_api_dir }}/node_modules state=link

- name: install npm modules
  npm: path={{ cocorico_api_dir }}

- name: generate the documentation
  shell: npm run doc
  args:
    chdir: "{{ cocorico_api_dir }}"

- name: generate configuration
  template: src=config.json.j2 dest={{ project_dir }}/{{ role_name }}/config.json
  notify:
    - restart cocorico-api-web service

- name: create admin
  when: is_development_environment
  shell: "{{ cocorico_api_dir }}/scripts/add-admin.js
    --email={{ api_web_admin_email }}
    --password={{ api_web_admin_password }}
    --username={{ api_web_admin_name }}
    --isAdmin=true"
  args:
    chdir: "{{ cocorico_api_dir }}"
  register: result
  changed_when: "'created' in result.stdout"
  failed_when: result.stderr

- name: create test app
  when: test_app is defined
  shell: "{{ cocorico_api_dir }}/scripts/add-app.js
    --title={{ test_app.title }}
    --secret={{ test_app.secret }}
    --url={{ test_app.url }}"
  args:
    chdir: "{{ cocorico_api_dir }}"
  register: create_api_test_app
  changed_when: "'created' in create_api_test_app.stdout"
  failed_when: create_api_test_app.stderr

- name: update configuration
  template: src=config.json.j2 dest={{ project_dir }}/{{ role_name }}/config.json
  when: create_api_test_app
  notify:
    - restart cocorico-api-web service

- name: import pages
  shell: "./import-pages.js"
  args:
    chdir: "{{ cocorico_api_dir }}/scripts"
  register: result
  failed_when: result.stderr
  changed_when: "'Updated page' in result.stdout"

- name: whitelist IPs
  shell: "{{ cocorico_api_dir }}/scripts/whitelist-ip.js --ip={{ item }}"
  args:
    chdir: "{{ cocorico_api_dir }}"
  register: result
  failed_when: result.stderr
  changed_when: "'already whitelisted' not in result.stdout"
  with_items: "{{ whitelisted_ips }}"
  when: whitelisted_ips is defined

- name: link app configuration
  file: src={{ project_dir }}/{{ role_name }}/config.json dest={{ cocorico_api_dir }}/config.json state=link

- name: install upstart script
  template: src={{ role_name }}.upstart.conf.j2 dest=/etc/init/{{ project_name }}-{{ role_name }}.conf
  notify:
    - restart cocorico-api-web service

- name: install site configuration
  template: src={{ role_name }}.apache.conf.j2 dest=/etc/apache2/sites-available/cocorico-front-web-include/{{ project_name }}-{{ role_name }}.conf
  notify:
    - restart apache2 service

- name: start the service
  service: name=cocorico-api-web state=restarted
